

"""add profile fields to user

Revision ID: 77f39e73372b
Revises: a8b9c0d1e2f3
Create Date: 2026-04-28 11:10:34.648568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '77f39e73372b'
down_revision: Union[str, None] = 'a8b9c0d1e2f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notices', 'keyword_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.add_column('users', sa.Column('language_institute_status', sa.String(), nullable=True))
    op.add_column('users', sa.Column('language_institute_term', sa.String(), nullable=True))
    op.add_column('users', sa.Column('target_admission_term', sa.String(), nullable=True))
    op.add_column('users', sa.Column('desired_major', sa.String(), nullable=True))
    op.add_column('users', sa.Column('visa_type', sa.String(), nullable=True))
    op.add_column('users', sa.Column('visa_expiry_date', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('visa_expiry_unknown', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('topik_status', sa.String(), nullable=True))
    op.add_column('users', sa.Column('topik_level', sa.String(), nullable=True))
    op.add_column('users', sa.Column('topik_target_level', sa.String(), nullable=True))
    op.add_column('users', sa.Column('topik_test_plan', sa.String(), nullable=True))
    op.add_column('users', sa.Column('preferred_language', sa.String(), server_default='English', nullable=False))
    op.add_column('users', sa.Column('residence_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'residence_type')
    op.drop_column('users', 'preferred_language')
    op.drop_column('users', 'topik_test_plan')
    op.drop_column('users', 'topik_target_level')
    op.drop_column('users', 'topik_level')
    op.drop_column('users', 'topik_status')
    op.drop_column('users', 'visa_expiry_unknown')
    op.drop_column('users', 'visa_expiry_date')
    op.drop_column('users', 'visa_type')
    op.drop_column('users', 'desired_major')
    op.drop_column('users', 'target_admission_term')
    op.drop_column('users', 'language_institute_term')
    op.drop_column('users', 'language_institute_status')
    op.alter_column('notices', 'keyword_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###
