

"""fix_embedding_size

Revision ID: cf02b2a86bf8
Revises: 6f4a2d1c9e11
Create Date: 2026-03-18 21:00:35.309902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cf02b2a86bf8'
down_revision: Union[str, None] = '6f4a2d1c9e11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.drop_table('topik_schedules')
    op.add_column('notices', sa.Column('embedding', pgvector.sqlalchemy.VECTOR(dim=1536), nullable=True))
    op.drop_constraint(op.f('notices_dedupe_hash_key'), 'notices', type_='unique')
    op.drop_column('notices', 'source_url')
    op.drop_column('notices', 'notice_tag')
    op.drop_column('notices', 'deadline_at')
    op.drop_column('notices', 'dedupe_hash')
    op.drop_column('notices', 'updated_at')
    op.drop_column('notices', 'published_at_inferred')
    op.drop_column('notices', 'is_embedded')
    op.drop_column('notices', 'is_deleted')
    op.drop_column('notices', 'source_type')
    op.drop_column('notices', 'published_at_confidence')
    op.drop_column('notices', 'published_at_final')
    op.drop_column('notices', 'published_at_raw')
    op.drop_column('notices', 'content_hash')
    op.drop_column('notices', 'source_name')
    op.drop_column('notices', 'deadline_text')
    op.drop_column('notices', 'category_final')
    op.drop_column('notices', 'category_reason')
    op.drop_column('notices', 'source_notice_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notices', sa.Column('source_notice_id', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('notices', sa.Column('category_reason', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('notices', sa.Column('category_final', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('notices', sa.Column('deadline_text', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('notices', sa.Column('source_name', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('notices', sa.Column('content_hash', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('notices', sa.Column('published_at_raw', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('notices', sa.Column('published_at_final', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('notices', sa.Column('published_at_confidence', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('notices', sa.Column('source_type', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('notices', sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('notices', sa.Column('is_embedded', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('notices', sa.Column('published_at_inferred', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('notices', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('notices', sa.Column('dedupe_hash', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('notices', sa.Column('deadline_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('notices', sa.Column('notice_tag', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('notices', sa.Column('source_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('notices_dedupe_hash_key'), 'notices', ['dedupe_hash'], postgresql_nulls_not_distinct=False)
    op.drop_column('notices', 'embedding')
    op.create_table('topik_schedules',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('category', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('round_label', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('apply_start', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('apply_end', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('apply_status', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('exam_date_kr', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('exam_date_global', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('exam_date_asia', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('exam_level', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('result_announce_at', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('notice_link', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('source_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('topik_schedules_pkey')),
    sa.UniqueConstraint('category', 'round_label', name=op.f('topik_schedules_category_round_label_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
