# 파일 기능: 초기 스키마를 생성하는 Alembic 마이그레이션이다.
"""baseline schema

Revision ID: e97b8af26a78
Revises: 
Create Date: 2026-02-27 16:53:19.437942

"""
from typing import Sequence, Union
# op: Alembic 의 operation 객체, migration 안에서 실제 DB 변경 작업을 수행하는 도구
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e97b8af26a78'
# 이전 버전 migration
down_revision: Union[str, None] = None
# 고급 migration 관리용; 당장은 신경쓰지 말기
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# DB를 앞으로 진행시키는 함수
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    
    op.create_table('categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    
    op.create_table('keywords',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    
    op.create_table('notices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('notice_id', sa.String(), nullable=False),
    sa.Column('category_key', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('preview', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('hash', sa.String(), nullable=True),
    sa.Column('is_processed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notices_category_key'), 'notices', ['category_key'], unique=False)
    op.create_index('ix_notices_category_published', 'notices', ['category_key', 'published_at'], unique=False)
    op.create_index(op.f('ix_notices_notice_id'), 'notices', ['notice_id'], unique=True)
    op.create_index('ix_notices_preview_trgm', 'notices', ['preview'], unique=False, postgresql_using='gin', postgresql_ops={'preview': 'gin_trgm_ops'})
    op.create_index(op.f('ix_notices_published_at'), 'notices', ['published_at'], unique=False)
    op.create_index('ix_notices_title_trgm', 'notices', ['title'], unique=False, postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    
    op.create_table('alert_outbox',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('notice_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), server_default='pending', nullable=False),
    sa.Column('try_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['notice_id'], ['notices.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'notice_id', name='uq_alert_outbox_user_notice')
    )
    op.create_index('ix_alert_outbox_status_created_at', 'alert_outbox', ['status', 'created_at'], unique=False)
    
    op.create_table('notice_keywords',
    sa.Column('notice_id', sa.UUID(), nullable=False),
    sa.Column('keyword_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], ),
    sa.ForeignKeyConstraint(['notice_id'], ['notices.id'], ),
    sa.PrimaryKeyConstraint('notice_id', 'keyword_id')
    )
    op.create_index('ix_notice_keywords_keyword_id', 'notice_keywords', ['keyword_id'], unique=False)
    
    op.create_table('user_keywords',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('keyword_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'keyword_id')
    )
    op.create_index('ix_user_keywords_keyword_id', 'user_keywords', ['keyword_id'], unique=False)
    # ### end Alembic commands ###

# DB를 이전 상태로 되돌리는 함수
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_keywords_keyword_id', table_name='user_keywords')
    op.drop_table('user_keywords')
    
    op.drop_index('ix_notice_keywords_keyword_id', table_name='notice_keywords')
    op.drop_table('notice_keywords')
    
    op.drop_index('ix_alert_outbox_status_created_at', table_name='alert_outbox')
    op.drop_table('alert_outbox')
    
    op.drop_table('users')
    
    op.drop_index('ix_notices_title_trgm', table_name='notices', postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.drop_index(op.f('ix_notices_published_at'), table_name='notices')
    op.drop_index('ix_notices_preview_trgm', table_name='notices', postgresql_using='gin', postgresql_ops={'preview': 'gin_trgm_ops'})
    op.drop_index(op.f('ix_notices_notice_id'), table_name='notices')
    op.drop_index('ix_notices_category_published', table_name='notices')
    op.drop_index(op.f('ix_notices_category_key'), table_name='notices')
    op.drop_table('notices')
    
    op.drop_table('keywords')
    
    op.drop_table('categories')
    # ### end Alembic commands ###
